#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: Vote 3 - Economic And Small Business Development, Tourism And Environmental
      Affairs
    url: https://data.vulekamali.gov.za/dataset/da4b8658-8126-4cc9-bb68-31546075acb8/resource/0f791799-813f-4fd3-b568-f6ec01587ac1/download/fs-vote-03-economic-development-tourism-and-enviroment.pdf
  name: 'Free State Department: Economic And Small Business Development, Tourism And
    Environmental Affairs 2018-19'
  tables: null
description: 'Free State department: Economic And Small Business Development, Tourism
  And Environmental Affairs budget data for the 2018-19 financial year from National
  Treasury in partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Free%2BState%2522%257Cdepartment.department%253A%2522Economic%2BAnd%2BSmall%2BBusiness%2BDevelopment%252C%2BTourism%2BAnd%2BEnvironmental%2BAffairs%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 97493000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 60137000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 2794000.0
        type: economic_classification_2
      - name: Software And Other Intangible Assets
        total_budget: 20000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 4000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Goods And Services
        total_budget: 88552000.0
        type: economic_classification_2
      - name: Compensation Of Employees
        total_budget: 46607000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 1085000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 112327000.0
        type: economic_classification_2
      - name: Public Corporations And Private Enterprises
        total_budget: 43833000.0
        type: economic_classification_2
      - name: Foreign Governments And International Organisations
        total_budget: 2000000.0
        type: economic_classification_2
      - name: Households
        total_budget: 1179000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Economic And Small Business Development
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 92344000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 48011000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Buildings And Other Fixed Structures
        total_budget: 21498000.0
        type: economic_classification_2
      - name: Machinery And Equipment
        total_budget: 1315000.0
        type: economic_classification_2
      - name: Software And Other Intangible Assets
        total_budget: 300000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 202000.0
        type: economic_classification_2
      - name: Households
        total_budget: 100000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 9403000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 2419000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 308000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2018-19
    nominal:
    - amount: 429772000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 463414000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 463076000.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 505148000.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 631931000.0
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 632942000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 675859000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 527792133
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 541146437
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 508726682
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 529961840
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 631931000
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 601895538
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 609324495
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: true
- closest_match:
    is_exact_match: false
    url_path: /2019-20/provincial/free-state
  id: 2019-20
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Mandate\n\n\nThere are several legislations and policies that the Department\
  \ has to operate within as it conducts its mandate. Below is the main legislation\
  \ the Department has to comply to:\n\n * Tourism second amendment Act, 2000 (Act\
  \ No.70 of 2000)\n * National Environmental Management Act No. 107 of 1998, as amended\n\
  \ * Environment Conservation Act No. 73 of 1989, as amended\n * National Environmental\
  \ Management: Air Quality Management Act No. 39 of 2004\n * NEM: Biodiversity Act,\
  \ 2004 (Act No.10 of 2004)\n * NEM: Protected Areas Act, 2003 (Act No. 57 of 2003)\n\
  \ * The Free State Nature Conservation Ordinance,1969 (Ord. No.8 of 1969)\n * Environment\
  \ Conservation Act of 1989, as amended.\n * World Heritage Conservation Act, 1999\n\
  \ * Conservation of Agricultural Resources Act, 1983 (Act No. 43 of 1983)\n * Animal\
  \ Protection Act, 1962 (Act No. 71 of 1962)\n * National Forest Act, 1998 (Act No.\
  \ 84 of 1998)\n * Veld and Forest Fire Act, 1998 (Act No. 101 of 1998)\n * Game\
  \ Theft Act, 1991 (Act No. 105 of 1991)\n * National Heritage Resources, 1999 (\
  \ Act No. 25 of 1999)\n * National Water Act, 1998 (Act No. 36 of 1998)\n * Co-operative\
  \ Act, 2005 (Act No 14. of  2005)\n\n## Vision\n\nA transformed economy and a prosperous\
  \ society that is living in harmony with its natural resources through integrated\
  \ and sustainable economic growth.\n\n## Mission\n\nRadically create a conducive,\
  \ enabling environment for the creation of decent jobs, poverty and inequality reduction\
  \ through sustainably managed environment and economic development programmes in\
  \ the Free State\n\n"
is_vote_primary: true
name: Economic And Small Business Development, Tourism And Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Free%2BState%2522%257Cdepartment.department%253A%2522Economic%2BAnd%2BSmall%2BBusiness%2BDevelopment%252C%2BTourism%2BAnd%2BEnvironmental%2BAffairs%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Administration
      total_budget: 97493000.0
      type: programme
    - name: Environmental Affairs
      total_budget: 92344000.0
      type: programme
    - name: Economic And Small Business Development
      total_budget: 46607000.0
      type: programme
    - name: Tourism
      total_budget: 9403000.0
      type: programme
    name: Current Payments - Compensation Of Employees
    type: economic_classification_1_and_2
  - items:
    - name: Economic And Small Business Development
      total_budget: 88552000.0
      type: programme
    - name: Administration
      total_budget: 60137000.0
      type: programme
    - name: Environmental Affairs
      total_budget: 48011000.0
      type: programme
    - name: Tourism
      total_budget: 2419000.0
      type: programme
    name: Current Payments - Goods And Services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 21498000.0
      type: programme
    name: Payments For Capital Assets - Buildings And Other Fixed Structures
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2794000.0
      type: programme
    - name: Environmental Affairs
      total_budget: 1315000.0
      type: programme
    - name: Economic And Small Business Development
      total_budget: 1085000.0
      type: programme
    - name: Tourism
      total_budget: 308000.0
      type: programme
    name: Payments For Capital Assets - Machinery And Equipment
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 300000.0
      type: programme
    - name: Administration
      total_budget: 20000.0
      type: programme
    name: Payments For Capital Assets - Software And Other Intangible Assets
    type: economic_classification_1_and_2
  - items:
    - name: Economic And Small Business Development
      total_budget: 112327000.0
      type: programme
    - name: Environmental Affairs
      total_budget: 202000.0
      type: programme
    - name: Administration
      total_budget: 4000.0
      type: programme
    name: Transfers And Subsidies - Departmental Agencies And Accounts
    type: economic_classification_1_and_2
  - items:
    - name: Economic And Small Business Development
      total_budget: 2000000.0
      type: programme
    name: Transfers And Subsidies - Foreign Governments And International Organisations
    type: economic_classification_1_and_2
  - items:
    - name: Economic And Small Business Development
      total_budget: 1179000.0
      type: programme
    - name: Environmental Affairs
      total_budget: 100000.0
      type: programme
    name: Transfers And Subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Economic And Small Business Development
      total_budget: 43833000.0
      type: programme
    name: Transfers And Subsidies - Public Corporations And Private Enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Free%2BState%2522%257Cdepartment.department%253A%2522Economic%2BAnd%2BSmall%2BBusiness%2BDevelopment%252C%2BTourism%2BAnd%2BEnvironmental%2BAffairs%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 160448000.0
  - name: Environmental Affairs
    total_budget: 163770000.0
  - name: Economic And Small Business Development
    total_budget: 295583000.0
  - name: Tourism
    total_budget: 12130000.0
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-drilldown-2018-19-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Free%2BState%2522%257Cdepartment.department%253A%2522Economic%2BAnd%2BSmall%2BBusiness%2BDevelopment%252C%2BTourism%2BAnd%2BEnvironmental%2BAffairs%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme.programme%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Economic And Small Business Development, Tourism And Environmental Affairs
  budget 2018-19  - vulekamali
vote_number: 3
vote_primary:
  name: Economic And Small Business Development, Tourism And Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
website_url: null
