#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget: null
description: 'KwaZulu-Natal department: Economic Development, Tourism and Environmental
  Affairs  budget data for the 2019-20 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522KwaZulu-Natal%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BTourism%2Band%2BEnvironmental%2BAffairs%2B%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programmes: []
expenditure_over_time: null
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2019-20/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2019-20
  is_selected: true
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: ''
is_vote_primary: true
name: 'Economic Development, Tourism and Environmental Affairs '
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522KwaZulu-Natal%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BTourism%2Band%2BEnvironmental%2BAffairs%2B%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  econ_classes: []
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522KwaZulu-Natal%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BTourism%2Band%2BEnvironmental%2BAffairs%2B%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programme_budgets: []
selected_financial_year: 2019-20
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522KwaZulu-Natal%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BTourism%2Band%2BEnvironmental%2BAffairs%2B%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programmes: []
title: Economic Development, Tourism and Environmental Affairs  budget 2019-20  -
  vulekamali
vote_number: 4
vote_primary:
  name: 'Economic Development, Tourism and Environmental Affairs '
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2019-20/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
website_url: null
