#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: Vote 6 - Economic Development, Environment And Tourism
    url: https://data.vulekamali.gov.za/dataset/95eda5cb-c3c4-4d60-ba28-b7891b4f98f2/resource/acf32d84-5c97-418f-acbd-92914dda1ce3/download/lim-vote-06-economic-dev.-environ.-tourism.pdf
  name: 'Limpopo Department: Economic Development, Environment And Tourism 2018-19'
  tables: null
description: 'Limpopo department: Economic Development, Environment And Tourism budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2BAnd%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 192442416.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 169454232.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 22352394.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 7292936.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 2619276.0
        type: economic_classification_2
      - name: Departmental Agencies And Accounts
        total_budget: 129639.99999999999
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 78965000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 30456922.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Buildings And Other Fixed Structures
        total_budget: 2481010.0
        type: economic_classification_2
      - name: Software And Other Intangible Assets
        total_budget: 300.0
        type: economic_classification_2
      - name: Land And Sub-Soil Assets
        total_budget: 200.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 637361000.0
        type: economic_classification_2
      - name: Households
        total_budget: 299414.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Economic Development
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 276688000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 48014442.0
        type: economic_classification_2
      - name: Interest And Rent On Land
        total_budget: 919622.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Buildings And Other Fixed Structures
        total_budget: 52000000.0
        type: economic_classification_2
      - name: Machinery And Equipment
        total_budget: 1528246.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 3126028.0
        type: economic_classification_2
      - name: Non-Profit Institutions
        total_budget: 754000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 699700.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 16887000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 11692760.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 109209000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2018-19
    nominal:
    - amount: 1112393000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1153443000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1312225000.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1694971000.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 1665373538.0
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 1668288000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 1752013000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 1366101734
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1346919969
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1441585984
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1778231231
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 1665373538
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 1586456744
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 1579537206
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2018-19
  is_selected: true
- closest_match:
    is_exact_match: false
    url_path: /2019-20/provincial/limpopo
  id: 2019-20
  is_selected: false
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environment And Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2BAnd%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 276688000.0
      type: programme
    - name: Administration
      total_budget: 192442416.0
      type: programme
    - name: Economic Development
      total_budget: 78965000.0
      type: programme
    - name: Tourism
      total_budget: 16887000.0
      type: programme
    name: Current Payments - Compensation Of Employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 169454232.0
      type: programme
    - name: Environmental Affairs
      total_budget: 48014442.0
      type: programme
    - name: Economic Development
      total_budget: 30456922.0
      type: programme
    - name: Tourism
      total_budget: 11692760.0
      type: programme
    name: Current Payments - Goods And Services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 919622.0
      type: programme
    name: Current Payments - Interest And Rent On Land
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 52000000.0
      type: programme
    - name: Economic Development
      total_budget: 2481010.0
      type: programme
    name: Payments For Capital Assets - Buildings And Other Fixed Structures
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 200.0
      type: programme
    name: Payments For Capital Assets - Land And Sub-Soil Assets
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 22352394.0
      type: programme
    - name: Environmental Affairs
      total_budget: 1528246.0
      type: programme
    name: Payments For Capital Assets - Machinery And Equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 300.0
      type: programme
    name: Payments For Capital Assets - Software And Other Intangible Assets
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 637361000.0
      type: programme
    - name: Tourism
      total_budget: 109209000.0
      type: programme
    - name: Administration
      total_budget: 129639.99999999999
      type: programme
    name: Transfers And Subsidies - Departmental Agencies And Accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 7292936.0
      type: programme
    - name: Environmental Affairs
      total_budget: 3126028.0
      type: programme
    - name: Economic Development
      total_budget: 299414.0
      type: programme
    name: Transfers And Subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 754000.0
      type: programme
    name: Transfers And Subsidies - Non-Profit Institutions
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2619276.0
      type: programme
    - name: Environmental Affairs
      total_budget: 699700.0
      type: programme
    name: Transfers And Subsidies - Provinces And Municipalities
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2BAnd%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 394290894.0
  - name: Economic Development
    total_budget: 749563846.0
  - name: Environmental Affairs
    total_budget: 383730038.0
  - name: Tourism
    total_budget: 137788760.0
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-drilldown-2018-19-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2BAnd%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme.programme%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Economic Development, Environment And Tourism budget 2018-19  - vulekamali
vote_number: 6
vote_primary:
  name: Economic Development, Environment And Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
website_url: null
